DROP TABLE IF EXISTS bookings, items, requests, users, comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY    PRIMARY KEY,
    name            VARCHAR(100)                                        NOT NULL,
    email           VARCHAR(100)                                        NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_unique_email_idx ON users(email);

CREATE TABLE IF NOT EXISTS requests (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY    PRIMARY KEY,
    description     VARCHAR(1000)                                       NOT NULL,
    requester_id    BIGINT          REFERENCES users(id)                ON DELETE CASCADE,
    created         TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY    PRIMARY KEY,
    name            VARCHAR(100)                                        NOT NULL,
    description     VARCHAR(1000)                                       NOT NULL,
    is_available    BOOLEAN         DEFAULT FALSE                       NOT NULL,
    owner_id        BIGINT          REFERENCES users(id)                ON DELETE CASCADE,
    request_id      BIGINT          REFERENCES requests(id)             ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY    PRIMARY KEY,
    start_date      TIMESTAMP WITHOUT TIME ZONE,
    end_date        TIMESTAMP WITHOUT TIME ZONE,
    item_id         BIGINT          REFERENCES items(id)                ON DELETE CASCADE,
    booker_id       BIGINT          REFERENCES users(id)                ON DELETE CASCADE,
    status          VARCHAR(100)                                        NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY    PRIMARY KEY,
    text            VARCHAR(1000)                                       NOT NULL,
    item_id         BIGINT          REFERENCES items(id)                ON DELETE CASCADE,
    author_id       BIGINT          REFERENCES users(id)                ON DELETE CASCADE,
    created         TIMESTAMP WITHOUT TIME ZONE
);